### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by nealioa** [tuckermitcht/mtucker5.github.io#1]
index.html

line 113: Where's the closing tag for the `<p>`?

styles.css

line 227: Add spaces around the `>`. E.g. `.socials > i`

line 219: If it's commented out, it's not needed. Delete it.

line 5, 24, etc: Unnecessary blank line. Delete it.

**Comment by tuckermitcht** [comment]
All done 👍

**Comment by nealioa** [comment]
Thanks
